import { AxeIcon } from 'lucide-react'
import React from 'react'

type Props = {}

const NotFound = (props: Props) => {
  return (
    <div className="flex flex-col min-h-[70vh] w-full justify-center items-center gap-10 bg-gradient-to-br from-background to-muted/40 rounded-xl shadow-inner animate-fadeIn">
      <div className="p-6 rounded-full bg-muted shadow-lg transform hover:scale-105 transition-transform duration-300">
        <AxeIcon className="w-12 h-12 text-primary animate-wiggle" />
      </div>

      <div className="flex flex-col items-center justify-center text-center">
        <p className="text-4xl font-bold text-primary drop-shadow-md tracking-tight">
          Nothing to see here
        </p>
        <p className="text-base text-muted-foreground mt-2 max-w-sm leading-relaxed">
          So here's a random image generated by <span className="text-vivid font-semibold">Creative AI</span>
        </p>
      </div>
    </div>
  )
}

export default NotFound
